export const tableData = [
  {
    "no": 1,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Ajinomoto Professional ID",
    "category": "FnB",
    "quarter": "Q2",
    "platform": "Instagram, Youtube",
    "sow": "Social Media Handling",
    "content": "-",
    "status": "On Going",
    "date": "2025-07-03",
    "link": "-"
  },
  {
    "no": 2,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Milkita",
    "category": "FMCG",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "Social Media Handling",
    "content": "-",
    "status": "Development",
    "date": "2025-07-03",
    "link": "-"
  },
  {
    "no": 3,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "IF Coconut Water",
    "category": "FMCG",
    "quarter": "Q3",
    "platform": "TikTok",
    "sow": "KOL Management",
    "content": "Launching Brand In Indonesia",
    "status": "Development",
    "date": "2025-07-03",
    "link": "-"
  },
  {
    "no": 4,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Galeri 24",
    "category": "Jewelery",
    "quarter": "Q2",
    "platform": "TikTok",
    "sow": "KOL Management",
    "content": "Event Video Recap",
    "status": "Published",
    "date": "2025-07-03",
    "link": "-"
  },
  {
    "no": 5,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Bli Bli",
    "category": "E-commerce",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "-",
    "status": "On Going",
    "date": "2025-07-03",
    "link": "-"
  },
  {
    "no": 6,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Maybelline",
    "category": "Beauty",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Video",
    "content": "Awareness for Maybelline Birthday Concert",
    "status": "Published",
    "date": "2025-07-03",
    "link": "https://www.instagram.com/p/DJNr3puyBIq/?igsh=NXB6NWpvbWVwaG5s"
  },
  {
    "no": 7,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "EXTRAJOSS",
    "category": "FMCG",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Reels",
    "content": "Highlight Offline Activation CFD",
    "status": "Published",
    "date": "2025-07-03",
    "link": "https://www.instagram.com/reel/DJgiOfWSj1n/?igsh=MzcyNjI2Z3RsYTh4"
  },
  {
    "no": 8,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "CLEAR X GRAB",
    "category": "FMCG",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Reels",
    "content": "Mobile Offline Activation Info",
    "status": "Published",
    "date": "2025-07-03",
    "link": "https://www.instagram.com/reel/DJwWTlySbPY/?igsh=cjB4emI2NHJkbjQ1"
  },
  {
    "no": 9,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "BANGO",
    "category": "FMCG",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Photo",
    "content": "Idul Adha Moment Tap In",
    "status": "Published",
    "date": "2025-07-03",
    "link": "https://www.instagram.com/p/DKgb_cjS7KS/?img_index=2&igsh=dWc2YTRpenRhZjNz"
  },
  {
    "no": 10,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Sarga Pacuan Kuda",
    "category": "Service",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed ",
    "content": "Awareness of SARGA Event",
    "status": "Published",
    "date": "2025-07-03",
    "link": "https://www.instagram.com/p/DJLSAFvSpdv/?img_index=4&igsh=MXA5NXVyOG52ZnppOQ=="
  },
  {
    "no": 11,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Fuji Film",
    "category": "Electronic",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Reels",
    "content": "Release of New Products",
    "status": "Published",
    "date": "2025-07-03",
    "link": "https://www.instagram.com/reel/DIODYvjSxDm/?igsh=MTNxMXEwaGpkbGd1dQ=="
  },
  {
    "no": 12,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Karya Digital Madani",
    "category": "Service",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "2x IG Feed Video",
    "content": "Release of New Products",
    "status": "Published",
    "date": "2025-07-03",
    "link": "https://www.instagram.com/reel/DIODYvjSxDm/?igsh=MTNxMXEwaGpkbGd1dQ=="
  },
  {
    "no": 13,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Amero Jewelery",
    "category": "Jewelery",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Video",
    "content": "-",
    "status": "Development",
    "date": "2025-07-03",
    "link": "-"
  },
  {
    "no": 14,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Royal K-Sausage",
    "category": "FMCG",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Video",
    "content": "Launching Product RTE",
    "status": "Published",
    "date": "2025-07-03",
    "link": "https://www.instagram.com/p/DLb98AbS1Sk/?igsh=cmpjN201eGhuNGhv"
  },
  {
    "no": 15,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Samsung",
    "category": "Electronic",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Video",
    "content": "Launch Videoseries Awareness",
    "status": "Published",
    "date": "2025-07-03",
    "link": "https://www.instagram.com/p/DLUWXIJyFFh/?igsh=MXNmN3Y1enY2ZnlqcA=="
  },
  {
    "no": 16,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "BCA",
    "category": "Finance",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "3x IG Feed Video, 1x IG Reels",
    "content": "AntiFraud Campaign, AntiFraud Campaign",
    "status": "Published",
    "date": "2025-07-03",
    "link": "https://www.instagram.com/p/DLAE5yLSi8x/?img_index=2&igsh=MWR2NW5saDcwNDZuag=="
  },
  {
    "no": 17,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "DBL",
    "category": "Entertainment",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "2x IG Feed Video",
    "content": "DBL Team Winning Tournament in USA",
    "status": "Published",
    "date": "2025-07-03",
    "link": "https://www.instagram.com/p/DLJ8WBVyBxa/?igsh=M2g3ZXZrM3VoaWti"
  },
  {
    "no": 18,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Livin' by Mandiri",
    "category": "Finance",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x YouTube, 1x IG Feed, 1x IG Story,  1x IG Reels, 1x TikTok Video",
    "content": "Revamp UI of Livin' by Mandiri Mobile App, Revamp UI of Livin' by Mandiri Mobile App, Revamp UI of Livin' by Mandiri Mobile App, Revamp UI of Livin' by Mandiri Mobile App, Revamp UI of Livin' by Mandiri Mobile App",
    "status": "Published",
    "date": "2025-07-03",
    "link": "https://www.youtube.com/watch?v=Yi1mQR72Kfs&t=142s"
  },
  {
    "no": 19,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "OCBC",
    "category": "Finance",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Vdieo",
    "content": "Launching Kartu Kredit OCBC Star Wars Platinum",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DJOj4t4S2fx/?igsh=ODhvMjEydXU5N21n"
  },
  {
    "no": 20,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Shell",
    "category": "Oil Industry",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Photo",
    "content": "Orang yang mau diberangkatin VIP Experience nonton F1 di Singapura \"\"",
    "status": "Delivered",
    "date": "2025-07-02",
    "link": "-"
  },
  {
    "no": 21,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Go Food",
    "category": "Services App",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "2x IG Feed Photo",
    "content": "Untuk reveal fase teaser dan bangun awareness soal fitur utama GoFood FLASH (15 menit)",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DLhDTAVTkfa/?igsh=cG9wNng1d2VxMHF2"
  },
  {
    "no": 22,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Diamond",
    "category": "FMCG",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Photo",
    "content": "Diamond Rich Milk adalah susu yang menghasilkan rasa creamy konsisten ",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DLXJi9qSOO6/?img_index=2&igsh=MTg3a2YzbzFxc2tyMA=="
  },
  {
    "no": 23,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Disney+",
    "category": "Entertainment",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "4x IG Story",
    "content": "Promo Disney+ Hotstar",
    "status": "Published",
    "date": "2025-07-02",
    "link": "-"
  },
  {
    "no": 24,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Telkomsel x USS",
    "category": "Telecomunication",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Video",
    "content": "Telkomsel Anniversary ",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DKKLJq9yv7i/?igsh=eWppZ3V0NTB2cWJv"
  },
  {
    "no": 25,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Kementrian Kordinasi Pemberdayaan",
    "category": "Goverment",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Photo",
    "content": "Raise awareness about Perintis Berdaya, a strategic pilot program initiated by Kemenko PM.",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DKwiID_zxiu/?igsh=YXNieW5qcGpkMG9k"
  },
  {
    "no": 26,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Scarlett Whitening",
    "category": "Beauty",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Video",
    "content": "Program CSR Scarlett Beauty Impact.",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DKy-6wpS9KQ/?utm_source=ig_web_copy_link&igsh=MXh3OW55bHZxMGxhag=="
  },
  {
    "no": 27,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Yakult",
    "category": "FMCG",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Photo",
    "content": "Highlight new product",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DLB5YaLyHGZ/?img_index=4&igsh=MXh5Z2RrdDVjNzhrcQ=="
  },
  {
    "no": 28,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Plantiq Milk",
    "category": "FMCG",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Photo",
    "content": "Meningkatkan Awareness terhadap produk dan Campaign",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DKjyWdwyGYW/?igsh=N3hrbzQ0dmN3YWt4"
  },
  {
    "no": 29,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Telkomsel",
    "category": "Provider",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Video",
    "content": "Merayakan 30 tahun Telkomsel ",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DKKLJq9yv7i/?igsh=eWppZ3V0NTB2cWJv"
  },
  {
    "no": 30,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Yakult",
    "category": "FMCG",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Video",
    "content": "Highlight new product",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DKQ-O8jyZ_N/?igsh=Y2V1dmNlNTZrZm11"
  },
  {
    "no": 31,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "UNIQLO",
    "category": "Fashion",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Photo",
    "content": "Meningkatkan daya tarik produk Linen",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DJJvk4yy3dV/?img_index=1&igsh=MXBmNXozY3Ywbjlubw=="
  },
  {
    "no": 32,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "BOSCH",
    "category": "Automotive",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Video",
    "content": "Launch Event",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DJD1WC3SeM4/?img_index=1&igsh=ZmVvZnI1Nm9rdDkx"
  },
  {
    "no": 33,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Telkomsel",
    "category": "Provider",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Video, 1x IG Story",
    "content": "Digiland 2025, Digiland 2025",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DJ1ZltPylJQ/?igsh=dWQ2c2U1OXhxenE0"
  },
  {
    "no": 34,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Marvel",
    "category": "Entertainment",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Reels, 1x IG Feed, 1x IG Story",
    "content": "Thunderbolts, Thunderbolts, Thunderbolts",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DJRPnA9SMYl/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA== https://www.instagram.com/reel/DJIzbRMS0iG/?igsh=azdiYmw5N3Q2NHI4 https://www.instagram.com/p/DJGnqsISSFk/?igsh=Nzh2dnFrMGZ3eWZh"
  },
  {
    "no": 35,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Wipol",
    "category": "FMCG",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Video",
    "content": "Gerakan Masjid Bersih (GMB) 2025 di kota Jakarta.",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/reel/DHgVEfDzPJ7/?igsh=YTYzNHQ4a29ldzBl"
  },
  {
    "no": 36,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Pocari",
    "category": "FMCG",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "Billcom",
    "content": "Billcom",
    "status": "Published",
    "date": "2025-07-02",
    "link": "-"
  },
  {
    "no": 37,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Garuda Indonesia ",
    "category": "Transportstation",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Photo",
    "content": "kolaborasi Garuda Indonesia dan Singapore Airlines ",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DHh4MY9z6nl/?igsh=MW81MXIyZWtmZzQycg=="
  },
  {
    "no": 38,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "KAHF",
    "category": "Beauty",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "4x IG Reels + 1x IG Feed Video + 1x IG story ",
    "content": "Event Kahf  event Kahf - Pejuang Berkahf Talks sangat informatif dan seru abis",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://vt.tiktok.com/ZSMUKbKrY/"
  },
  {
    "no": 39,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Gopay Split Bill",
    "category": "Finance",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Reels ",
    "content": " Fitur Split Bill di aplikasi GoPay.",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/reel/DHYcD9yT88r/?igsh=MWtkcjFiZnA4ZXFzZg=="
  },
  {
    "no": 40,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Air Asia",
    "category": "Transportstation",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Photo",
    "content": "Discount All Seat",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DHDg_o1TV6Y/?igsh=OGQ4ajFzMTV4aHA4"
  },
  {
    "no": 41,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Gopay",
    "category": "Services App",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed VIdeo",
    "content": "Gopay Hadiah THR ",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DHCw-M4z2Ue/?img_index=1&igsh=c2VrZnFuZW9rdmg="
  },
  {
    "no": 42,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Telkomsel",
    "category": "Provider",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Video+ 2 asset video ",
    "content": "Event Video Recap",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DG-JSH9yRXK/?img_index=2&igsh=N240Y3lycXNsOGR4"
  },
  {
    "no": 43,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Makeover",
    "category": "Beauty",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Video + Photo",
    "content": "MAKEOVER MASTERSHADE XR ",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DLUzkuhS-1v/?igsh=ZGhtcWdzemFkbHJw"
  },
  {
    "no": 44,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Papion",
    "category": "Entertainment",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Photo",
    "content": "Girl Group Launch",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DLRh4irynPK/?igsh=MWxwcXlrNmt2NjR5bw=="
  },
  {
    "no": 45,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Video",
    "content": "Lifebuoy OOH Cipung Skinfluencer",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DLCN7FpS_w_/?img_index=1&igsh=NXNrenh5d3BpdTUy"
  },
  {
    "no": 46,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Spotify",
    "category": "Application",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Story & 1x IG Feed Photo",
    "content": "Spotify #SupportifyIndonesia",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DKhezYSycCJ/?igsh=Y3M1aXFieGs2ZDF0"
  },
  {
    "no": 47,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Gillete",
    "category": "FMCG",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Video",
    "content": "Gillete x Pandawara",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4eRBVyHrL/?igsh=MTQ2dHJsYXpiMGE5Yw=="
  },
  {
    "no": 48,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Nivea",
    "category": "FMCG",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Video",
    "content": "Nivea x Tiktok Beauty Fest",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4eRBVyHrL/?igsh=MTQ2dHJsYXpiMGE5Yw=="
  },
  {
    "no": 49,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lazada",
    "category": "E-commerce",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x IG Feed Video",
    "content": "Lazada 6.6 WOW Sale ID",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DKcBkoJy-qz/?igsh=MWlpdHprYzZjazJjMg=="
  },
  {
    "no": 50,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q2",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 51,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q1",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q1",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q1",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q1",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q1",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q1",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q1",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q1",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q1",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q1",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q1",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q1",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q1",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q1",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q1",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Delivered",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
  {
    "no": 52,
    "source": "Outbound",
    "division": "Marketing",
    "brand": "Lifebuoy",
    "category": "FMCG",
    "quarter": "Q4",
    "platform": "Instagram",
    "sow": "1x Feed Video",
    "content": "Lifebuoy Merah Putih",
    "status": "Published",
    "date": "2025-07-02",
    "link": "https://www.instagram.com/p/DK4WNMvyBI0/?igsh=MWpwZGJ4d29hdXB4OA=="
  },
   
];